server:
  port: 0
spring:
  r2dbc:
    url: r2dbc:postgresql://192.168.0.250:5432/booking_tst
    name: postgresql
    username: resource
    password: '{cipher}eb56138ad5beb09bef691268bd396082251b65a51e1bc81b90d2da3532fd7aea'
    schema: "resource"
    repositories:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://avdeev-sa.ru/keycloak/realms/ttc-tops
          jwk-set-uri: https://avdeev-sa.ru/keycloak/realms/ttc-tops/protocol/openid-connect/certs
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://192.168.0.250:5432/booking_tst
    user: resource
    password: '{cipher}eb56138ad5beb09bef691268bd396082251b65a51e1bc81b90d2da3532fd7aea'
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
