server:
  port: 0
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/booking
    name: postgresql
    username: schedule
    password: '{cipher}5f697e69b202139460ef1ed466ad1e8112845baeda1c278883b8a131752da8f8'
    schema: "schedule"
    repositories:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://avdeev-sa.ru/keycloak/realms/booking_realm
          jwk-set-uri: https://avdeev-sa.ru/keycloak/realms/booking_realm/protocol/openid-connect/certs
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/booking
    user: schedule
    password: '{cipher}5f697e69b202139460ef1ed466ad1e8112845baeda1c278883b8a131752da8f8'
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    org.springframework.web.reactive: DEBUG
